spring:
  application:
    name: backend

  # TODO: Configure Neo4j URI here
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: testpassword
  output:
    ansi:
      enabled: always
